spring:
  application:
    name: sdk-client-dubbo
dubbo:
  application:
    name: ${spring.application.name}
    register-consumer: false
  registry:
    id: etcd
    address: etcd://@121.89.244.23:2379
    username: root
    password: dell123
    timeout: 15000
airiot:
  client:
    authorization:
      type: tenant
      app-key: 138dd03b-d3ee-4230-d3d2-520feb580bfe
      app-secret: 138dd03b-d3ee-4230-d3d2-520feb580bfd
    default-config:
      selectors:
        - metadata:
            env: aliyun
    services:
      core:
        enabled: true
      spm:
        enabled: true
      data-service:
        enabled: true
logging:
  level:
    cn.airiot.sdk.client.dubbo: DEBUG