#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  application:
    name: ${artifactId}
dubbo:
  application:
    name: ${symbol_dollar}{spring.application.name}
    register-consumer: false
  registry:
    id: etcd
    address: etcd://root:dell123@etcd:2379

airiot:
  driver:
    id: ${driverId}
    name: ${driverName}
  client:
    default-config:
      selectors:
        - metadata:
            env: local
    services:
      core:
        enabled: false
      spm:
        enabled: false
      data-service:
        enabled: false
      warning:
        enabled: false

logging:
  level:
    root: ${symbol_dollar}{LOG_LEVEL_ROOT:INFO}