#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
spring:
  application:
    name: ${artifactId}
#if (${enableClient} == "true")
dubbo:
  application:
    name: ${symbol_dollar}{spring.application.name}
    register-consumer: false
  registry:
    id: etcd
    address: etcd://127.0.0.1:2379
    username: root
    password: dell123
#end

airiot:
  driver:
    id: ${driverId}
    name: ${driverName}
#if (${enableClient} == "true")
  client:
    default-config:
      selectors:
        - metadata:
            env: local
    services:
      core:
        enabled: false
      spm:
        enabled: false
      data-service:
        enabled: false
      warning:
        enabled: false
#end
mq:
  mqtt:
    host: 127.0.0.1

driver-grpc:
  host: 127.0.0.1

logging:
  level:
    root: ${symbol_dollar}{LOG_LEVEL_ROOT:INFO}