// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

public final class Api {
  private Api() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_TokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_TokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_TokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_TokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_QueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_QueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_GetOrDeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_GetOrDeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_GetRequestName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_GetRequestName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\tapi.proto\022\003api\"&\n\014TokenRequest\022\n\n\002ak\030\001" +
      " \001(\t\022\n\n\002sk\030\002 \001(\t\"J\n\rTokenResponse\022\021\n\ttok" +
      "enType\030\001 \001(\t\022\021\n\texpiresAt\030\002 \001(\003\022\023\n\013acces" +
      "sToken\030\003 \001(\t\"\016\n\014EmptyRequest\"\035\n\014QueryReq" +
      "uest\022\r\n\005query\030\001 \001(\014\" \n\022GetOrDeleteReques" +
      "t\022\n\n\002id\030\001 \001(\t\"\036\n\016GetRequestName\022\014\n\004name\030" +
      "\001 \001(\t\")\n\rUpdateRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004da" +
      "ta\030\002 \001(\014\"\035\n\rCreateRequest\022\014\n\004data\030\001 \001(\014\"" +
      "V\n\010Response\022\016\n\006status\030\001 \001(\010\022\014\n\004code\030\002 \001(" +
      "\005\022\014\n\004info\030\003 \001(\t\022\016\n\006detail\030\004 \001(\t\022\016\n\006resul" +
      "t\030\005 \001(\014BT\n\035cn.airiot.sdk.driver.grpc.api" +
      "P\001Z+github.com/air-iot/api-client-go/v4/" +
      "api;api\210\001\001\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_api_TokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_TokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_TokenRequest_descriptor,
        new String[] { "Ak", "Sk", });
    internal_static_api_TokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_TokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_TokenResponse_descriptor,
        new String[] { "TokenType", "ExpiresAt", "AccessToken", });
    internal_static_api_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_EmptyRequest_descriptor,
        new String[] { });
    internal_static_api_QueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_QueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_QueryRequest_descriptor,
        new String[] { "Query", });
    internal_static_api_GetOrDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_GetOrDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_GetOrDeleteRequest_descriptor,
        new String[] { "Id", });
    internal_static_api_GetRequestName_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_GetRequestName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_GetRequestName_descriptor,
        new String[] { "Name", });
    internal_static_api_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_api_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_UpdateRequest_descriptor,
        new String[] { "Id", "Data", });
    internal_static_api_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_api_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_CreateRequest_descriptor,
        new String[] { "Data", });
    internal_static_api_Response_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_api_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_Response_descriptor,
        new String[] { "Status", "Code", "Info", "Detail", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
