// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
