// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
