// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes query = 1;</code>
   * @return The query.
   */
  com.google.protobuf.ByteString getQuery();
}
