// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

/**
 * Protobuf type {@code api.TokenResponse}
 */
public final class TokenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.TokenResponse)
    TokenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TokenResponse.newBuilder() to construct.
  private TokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TokenResponse() {
    tokenType_ = "";
    accessToken_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TokenResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TokenResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            tokenType_ = s;
            break;
          }
          case 16: {

            expiresAt_ = input.readInt64();
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();

            accessToken_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Api.internal_static_api_TokenResponse_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Api.internal_static_api_TokenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TokenResponse.class, Builder.class);
  }

  public static final int TOKENTYPE_FIELD_NUMBER = 1;
  private volatile Object tokenType_;
  /**
   * <code>string tokenType = 1;</code>
   * @return The tokenType.
   */
  @Override
  public String getTokenType() {
    Object ref = tokenType_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tokenType_ = s;
      return s;
    }
  }
  /**
   * <code>string tokenType = 1;</code>
   * @return The bytes for tokenType.
   */
  @Override
  public com.google.protobuf.ByteString
      getTokenTypeBytes() {
    Object ref = tokenType_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tokenType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXPIRESAT_FIELD_NUMBER = 2;
  private long expiresAt_;
  /**
   * <code>int64 expiresAt = 2;</code>
   * @return The expiresAt.
   */
  @Override
  public long getExpiresAt() {
    return expiresAt_;
  }

  public static final int ACCESSTOKEN_FIELD_NUMBER = 3;
  private volatile Object accessToken_;
  /**
   * <code>string accessToken = 3;</code>
   * @return The accessToken.
   */
  @Override
  public String getAccessToken() {
    Object ref = accessToken_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      accessToken_ = s;
      return s;
    }
  }
  /**
   * <code>string accessToken = 3;</code>
   * @return The bytes for accessToken.
   */
  @Override
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    Object ref = accessToken_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      accessToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tokenType_);
    }
    if (expiresAt_ != 0L) {
      output.writeInt64(2, expiresAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessToken_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accessToken_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tokenType_);
    }
    if (expiresAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, expiresAt_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accessToken_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accessToken_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TokenResponse)) {
      return super.equals(obj);
    }
    TokenResponse other = (TokenResponse) obj;

    if (!getTokenType()
        .equals(other.getTokenType())) return false;
    if (getExpiresAt()
        != other.getExpiresAt()) return false;
    if (!getAccessToken()
        .equals(other.getAccessToken())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKENTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTokenType().hashCode();
    hash = (37 * hash) + EXPIRESAT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiresAt());
    hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAccessToken().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TokenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TokenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TokenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TokenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TokenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TokenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TokenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TokenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TokenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TokenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TokenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.TokenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.TokenResponse)
      TokenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_api_TokenResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_api_TokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TokenResponse.class, Builder.class);
    }

    // Construct using cn.airiot.sdk.driver.grpc.api.TokenResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      tokenType_ = "";

      expiresAt_ = 0L;

      accessToken_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Api.internal_static_api_TokenResponse_descriptor;
    }

    @Override
    public TokenResponse getDefaultInstanceForType() {
      return TokenResponse.getDefaultInstance();
    }

    @Override
    public TokenResponse build() {
      TokenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TokenResponse buildPartial() {
      TokenResponse result = new TokenResponse(this);
      result.tokenType_ = tokenType_;
      result.expiresAt_ = expiresAt_;
      result.accessToken_ = accessToken_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TokenResponse) {
        return mergeFrom((TokenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TokenResponse other) {
      if (other == TokenResponse.getDefaultInstance()) return this;
      if (!other.getTokenType().isEmpty()) {
        tokenType_ = other.tokenType_;
        onChanged();
      }
      if (other.getExpiresAt() != 0L) {
        setExpiresAt(other.getExpiresAt());
      }
      if (!other.getAccessToken().isEmpty()) {
        accessToken_ = other.accessToken_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TokenResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TokenResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object tokenType_ = "";
    /**
     * <code>string tokenType = 1;</code>
     * @return The tokenType.
     */
    public String getTokenType() {
      Object ref = tokenType_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tokenType_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tokenType = 1;</code>
     * @return The bytes for tokenType.
     */
    public com.google.protobuf.ByteString
        getTokenTypeBytes() {
      Object ref = tokenType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tokenType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tokenType = 1;</code>
     * @param value The tokenType to set.
     * @return This builder for chaining.
     */
    public Builder setTokenType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tokenType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tokenType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenType() {
      
      tokenType_ = getDefaultInstance().getTokenType();
      onChanged();
      return this;
    }
    /**
     * <code>string tokenType = 1;</code>
     * @param value The bytes for tokenType to set.
     * @return This builder for chaining.
     */
    public Builder setTokenTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tokenType_ = value;
      onChanged();
      return this;
    }

    private long expiresAt_ ;
    /**
     * <code>int64 expiresAt = 2;</code>
     * @return The expiresAt.
     */
    @Override
    public long getExpiresAt() {
      return expiresAt_;
    }
    /**
     * <code>int64 expiresAt = 2;</code>
     * @param value The expiresAt to set.
     * @return This builder for chaining.
     */
    public Builder setExpiresAt(long value) {
      
      expiresAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expiresAt = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearExpiresAt() {
      
      expiresAt_ = 0L;
      onChanged();
      return this;
    }

    private Object accessToken_ = "";
    /**
     * <code>string accessToken = 3;</code>
     * @return The accessToken.
     */
    public String getAccessToken() {
      Object ref = accessToken_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string accessToken = 3;</code>
     * @return The bytes for accessToken.
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accessToken = 3;</code>
     * @param value The accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessToken(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string accessToken = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccessToken() {
      
      accessToken_ = getDefaultInstance().getAccessToken();
      onChanged();
      return this;
    }
    /**
     * <code>string accessToken = 3;</code>
     * @param value The bytes for accessToken to set.
     * @return This builder for chaining.
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessToken_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.TokenResponse)
  }

  // @@protoc_insertion_point(class_scope:api.TokenResponse)
  private static final TokenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TokenResponse();
  }

  public static TokenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenResponse>
      PARSER = new com.google.protobuf.AbstractParser<TokenResponse>() {
    @Override
    public TokenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TokenResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TokenResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TokenResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public TokenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

