// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

public interface TokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tokenType = 1;</code>
   * @return The tokenType.
   */
  String getTokenType();
  /**
   * <code>string tokenType = 1;</code>
   * @return The bytes for tokenType.
   */
  com.google.protobuf.ByteString
      getTokenTypeBytes();

  /**
   * <code>int64 expiresAt = 2;</code>
   * @return The expiresAt.
   */
  long getExpiresAt();

  /**
   * <code>string accessToken = 3;</code>
   * @return The accessToken.
   */
  String getAccessToken();
  /**
   * <code>string accessToken = 3;</code>
   * @return The bytes for accessToken.
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();
}
