// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

public interface TokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.TokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ak = 1;</code>
   * @return The ak.
   */
  String getAk();
  /**
   * <code>string ak = 1;</code>
   * @return The bytes for ak.
   */
  com.google.protobuf.ByteString
      getAkBytes();

  /**
   * <code>string sk = 2;</code>
   * @return The sk.
   */
  String getSk();
  /**
   * <code>string sk = 2;</code>
   * @return The bytes for sk.
   */
  com.google.protobuf.ByteString
      getSkBytes();
}
