// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api.proto

package cn.airiot.sdk.driver.grpc.api;

/**
 * Protobuf type {@code api.TokenRequest}
 */
public final class TokenRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.TokenRequest)
    TokenRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TokenRequest.newBuilder() to construct.
  private TokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TokenRequest() {
    ak_ = "";
    sk_ = "";
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new TokenRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TokenRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            ak_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            sk_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Api.internal_static_api_TokenRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Api.internal_static_api_TokenRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            TokenRequest.class, Builder.class);
  }

  public static final int AK_FIELD_NUMBER = 1;
  private volatile Object ak_;
  /**
   * <code>string ak = 1;</code>
   * @return The ak.
   */
  @Override
  public String getAk() {
    Object ref = ak_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      ak_ = s;
      return s;
    }
  }
  /**
   * <code>string ak = 1;</code>
   * @return The bytes for ak.
   */
  @Override
  public com.google.protobuf.ByteString
      getAkBytes() {
    Object ref = ak_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      ak_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SK_FIELD_NUMBER = 2;
  private volatile Object sk_;
  /**
   * <code>string sk = 2;</code>
   * @return The sk.
   */
  @Override
  public String getSk() {
    Object ref = sk_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      sk_ = s;
      return s;
    }
  }
  /**
   * <code>string sk = 2;</code>
   * @return The bytes for sk.
   */
  @Override
  public com.google.protobuf.ByteString
      getSkBytes() {
    Object ref = sk_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      sk_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ak_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ak_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sk_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sk_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ak_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ak_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(sk_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sk_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof TokenRequest)) {
      return super.equals(obj);
    }
    TokenRequest other = (TokenRequest) obj;

    if (!getAk()
        .equals(other.getAk())) return false;
    if (!getSk()
        .equals(other.getSk())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AK_FIELD_NUMBER;
    hash = (53 * hash) + getAk().hashCode();
    hash = (37 * hash) + SK_FIELD_NUMBER;
    hash = (53 * hash) + getSk().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static TokenRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TokenRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TokenRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TokenRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TokenRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static TokenRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static TokenRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TokenRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static TokenRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static TokenRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static TokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static TokenRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(TokenRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.TokenRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.TokenRequest)
      TokenRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Api.internal_static_api_TokenRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Api.internal_static_api_TokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TokenRequest.class, Builder.class);
    }

    // Construct using cn.airiot.sdk.driver.grpc.api.TokenRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      ak_ = "";

      sk_ = "";

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Api.internal_static_api_TokenRequest_descriptor;
    }

    @Override
    public TokenRequest getDefaultInstanceForType() {
      return TokenRequest.getDefaultInstance();
    }

    @Override
    public TokenRequest build() {
      TokenRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public TokenRequest buildPartial() {
      TokenRequest result = new TokenRequest(this);
      result.ak_ = ak_;
      result.sk_ = sk_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof TokenRequest) {
        return mergeFrom((TokenRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(TokenRequest other) {
      if (other == TokenRequest.getDefaultInstance()) return this;
      if (!other.getAk().isEmpty()) {
        ak_ = other.ak_;
        onChanged();
      }
      if (!other.getSk().isEmpty()) {
        sk_ = other.sk_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      TokenRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (TokenRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object ak_ = "";
    /**
     * <code>string ak = 1;</code>
     * @return The ak.
     */
    public String getAk() {
      Object ref = ak_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ak_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string ak = 1;</code>
     * @return The bytes for ak.
     */
    public com.google.protobuf.ByteString
        getAkBytes() {
      Object ref = ak_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ak_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ak = 1;</code>
     * @param value The ak to set.
     * @return This builder for chaining.
     */
    public Builder setAk(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ak_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ak = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAk() {
      
      ak_ = getDefaultInstance().getAk();
      onChanged();
      return this;
    }
    /**
     * <code>string ak = 1;</code>
     * @param value The bytes for ak to set.
     * @return This builder for chaining.
     */
    public Builder setAkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ak_ = value;
      onChanged();
      return this;
    }

    private Object sk_ = "";
    /**
     * <code>string sk = 2;</code>
     * @return The sk.
     */
    public String getSk() {
      Object ref = sk_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sk_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string sk = 2;</code>
     * @return The bytes for sk.
     */
    public com.google.protobuf.ByteString
        getSkBytes() {
      Object ref = sk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string sk = 2;</code>
     * @param value The sk to set.
     * @return This builder for chaining.
     */
    public Builder setSk(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sk_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string sk = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSk() {
      
      sk_ = getDefaultInstance().getSk();
      onChanged();
      return this;
    }
    /**
     * <code>string sk = 2;</code>
     * @param value The bytes for sk to set.
     * @return This builder for chaining.
     */
    public Builder setSkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sk_ = value;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.TokenRequest)
  }

  // @@protoc_insertion_point(class_scope:api.TokenRequest)
  private static final TokenRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new TokenRequest();
  }

  public static TokenRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenRequest>
      PARSER = new com.google.protobuf.AbstractParser<TokenRequest>() {
    @Override
    public TokenRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TokenRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TokenRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<TokenRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public TokenRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

