// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

/**
 * Protobuf type {@code driver.BatchRunRequest}
 */
public final class BatchRunRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:driver.BatchRunRequest)
    BatchRunRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BatchRunRequest.newBuilder() to construct.
  private BatchRunRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BatchRunRequest() {
    request_ = "";
    tableId_ = "";
    id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    serialNo_ = "";
    command_ = com.google.protobuf.ByteString.EMPTY;
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new BatchRunRequest();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BatchRunRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            String s = input.readStringRequireUtf8();

            request_ = s;
            break;
          }
          case 18: {
            String s = input.readStringRequireUtf8();

            tableId_ = s;
            break;
          }
          case 26: {
            String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              id_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            id_.add(s);
            break;
          }
          case 34: {
            String s = input.readStringRequireUtf8();

            serialNo_ = s;
            break;
          }
          case 42: {

            command_ = input.readBytes();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        id_ = id_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return Driver.internal_static_driver_BatchRunRequest_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return Driver.internal_static_driver_BatchRunRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            BatchRunRequest.class, Builder.class);
  }

  public static final int REQUEST_FIELD_NUMBER = 1;
  private volatile Object request_;
  /**
   * <code>string request = 1;</code>
   * @return The request.
   */
  @Override
  public String getRequest() {
    Object ref = request_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      request_ = s;
      return s;
    }
  }
  /**
   * <code>string request = 1;</code>
   * @return The bytes for request.
   */
  @Override
  public com.google.protobuf.ByteString
      getRequestBytes() {
    Object ref = request_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      request_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TABLEID_FIELD_NUMBER = 2;
  private volatile Object tableId_;
  /**
   * <code>string tableId = 2;</code>
   * @return The tableId.
   */
  @Override
  public String getTableId() {
    Object ref = tableId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      tableId_ = s;
      return s;
    }
  }
  /**
   * <code>string tableId = 2;</code>
   * @return The bytes for tableId.
   */
  @Override
  public com.google.protobuf.ByteString
      getTableIdBytes() {
    Object ref = tableId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      tableId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList id_;
  /**
   * <code>repeated string id = 3;</code>
   * @return A list containing the id.
   */
  public com.google.protobuf.ProtocolStringList
      getIdList() {
    return id_;
  }
  /**
   * <code>repeated string id = 3;</code>
   * @return The count of id.
   */
  public int getIdCount() {
    return id_.size();
  }
  /**
   * <code>repeated string id = 3;</code>
   * @param index The index of the element to return.
   * @return The id at the given index.
   */
  public String getId(int index) {
    return id_.get(index);
  }
  /**
   * <code>repeated string id = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the id at the given index.
   */
  public com.google.protobuf.ByteString
      getIdBytes(int index) {
    return id_.getByteString(index);
  }

  public static final int SERIALNO_FIELD_NUMBER = 4;
  private volatile Object serialNo_;
  /**
   * <code>string serialNo = 4;</code>
   * @return The serialNo.
   */
  @Override
  public String getSerialNo() {
    Object ref = serialNo_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      serialNo_ = s;
      return s;
    }
  }
  /**
   * <code>string serialNo = 4;</code>
   * @return The bytes for serialNo.
   */
  @Override
  public com.google.protobuf.ByteString
      getSerialNoBytes() {
    Object ref = serialNo_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      serialNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMMAND_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString command_;
  /**
   * <code>bytes command = 5;</code>
   * @return The command.
   */
  @Override
  public com.google.protobuf.ByteString getCommand() {
    return command_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(request_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, request_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tableId_);
    }
    for (int i = 0; i < id_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, id_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serialNo_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, serialNo_);
    }
    if (!command_.isEmpty()) {
      output.writeBytes(5, command_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(request_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, request_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tableId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tableId_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < id_.size(); i++) {
        dataSize += computeStringSizeNoTag(id_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIdList().size();
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serialNo_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, serialNo_);
    }
    if (!command_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, command_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof BatchRunRequest)) {
      return super.equals(obj);
    }
    BatchRunRequest other = (BatchRunRequest) obj;

    if (!getRequest()
        .equals(other.getRequest())) return false;
    if (!getTableId()
        .equals(other.getTableId())) return false;
    if (!getIdList()
        .equals(other.getIdList())) return false;
    if (!getSerialNo()
        .equals(other.getSerialNo())) return false;
    if (!getCommand()
        .equals(other.getCommand())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REQUEST_FIELD_NUMBER;
    hash = (53 * hash) + getRequest().hashCode();
    hash = (37 * hash) + TABLEID_FIELD_NUMBER;
    hash = (53 * hash) + getTableId().hashCode();
    if (getIdCount() > 0) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getIdList().hashCode();
    }
    hash = (37 * hash) + SERIALNO_FIELD_NUMBER;
    hash = (53 * hash) + getSerialNo().hashCode();
    hash = (37 * hash) + COMMAND_FIELD_NUMBER;
    hash = (53 * hash) + getCommand().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static BatchRunRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BatchRunRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BatchRunRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BatchRunRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BatchRunRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static BatchRunRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static BatchRunRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BatchRunRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static BatchRunRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static BatchRunRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static BatchRunRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static BatchRunRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(BatchRunRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code driver.BatchRunRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:driver.BatchRunRequest)
      BatchRunRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Driver.internal_static_driver_BatchRunRequest_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Driver.internal_static_driver_BatchRunRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              BatchRunRequest.class, Builder.class);
    }

    // Construct using cn.airiot.sdk.driver.grpc.driver.BatchRunRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      request_ = "";

      tableId_ = "";

      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      serialNo_ = "";

      command_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return Driver.internal_static_driver_BatchRunRequest_descriptor;
    }

    @Override
    public BatchRunRequest getDefaultInstanceForType() {
      return BatchRunRequest.getDefaultInstance();
    }

    @Override
    public BatchRunRequest build() {
      BatchRunRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public BatchRunRequest buildPartial() {
      BatchRunRequest result = new BatchRunRequest(this);
      int from_bitField0_ = bitField0_;
      result.request_ = request_;
      result.tableId_ = tableId_;
      if (((bitField0_ & 0x00000001) != 0)) {
        id_ = id_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.id_ = id_;
      result.serialNo_ = serialNo_;
      result.command_ = command_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof BatchRunRequest) {
        return mergeFrom((BatchRunRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(BatchRunRequest other) {
      if (other == BatchRunRequest.getDefaultInstance()) return this;
      if (!other.getRequest().isEmpty()) {
        request_ = other.request_;
        onChanged();
      }
      if (!other.getTableId().isEmpty()) {
        tableId_ = other.tableId_;
        onChanged();
      }
      if (!other.id_.isEmpty()) {
        if (id_.isEmpty()) {
          id_ = other.id_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIdIsMutable();
          id_.addAll(other.id_);
        }
        onChanged();
      }
      if (!other.getSerialNo().isEmpty()) {
        serialNo_ = other.serialNo_;
        onChanged();
      }
      if (other.getCommand() != com.google.protobuf.ByteString.EMPTY) {
        setCommand(other.getCommand());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      BatchRunRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (BatchRunRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private Object request_ = "";
    /**
     * <code>string request = 1;</code>
     * @return The request.
     */
    public String getRequest() {
      Object ref = request_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        request_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string request = 1;</code>
     * @return The bytes for request.
     */
    public com.google.protobuf.ByteString
        getRequestBytes() {
      Object ref = request_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        request_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string request = 1;</code>
     * @param value The request to set.
     * @return This builder for chaining.
     */
    public Builder setRequest(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      request_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string request = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequest() {
      
      request_ = getDefaultInstance().getRequest();
      onChanged();
      return this;
    }
    /**
     * <code>string request = 1;</code>
     * @param value The bytes for request to set.
     * @return This builder for chaining.
     */
    public Builder setRequestBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      request_ = value;
      onChanged();
      return this;
    }

    private Object tableId_ = "";
    /**
     * <code>string tableId = 2;</code>
     * @return The tableId.
     */
    public String getTableId() {
      Object ref = tableId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tableId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string tableId = 2;</code>
     * @return The bytes for tableId.
     */
    public com.google.protobuf.ByteString
        getTableIdBytes() {
      Object ref = tableId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tableId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableId = 2;</code>
     * @param value The tableId to set.
     * @return This builder for chaining.
     */
    public Builder setTableId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tableId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTableId() {
      
      tableId_ = getDefaultInstance().getTableId();
      onChanged();
      return this;
    }
    /**
     * <code>string tableId = 2;</code>
     * @param value The bytes for tableId to set.
     * @return This builder for chaining.
     */
    public Builder setTableIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableId_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIdIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        id_ = new com.google.protobuf.LazyStringArrayList(id_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string id = 3;</code>
     * @return A list containing the id.
     */
    public com.google.protobuf.ProtocolStringList
        getIdList() {
      return id_.getUnmodifiableView();
    }
    /**
     * <code>repeated string id = 3;</code>
     * @return The count of id.
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated string id = 3;</code>
     * @param index The index of the element to return.
     * @return The id at the given index.
     */
    public String getId(int index) {
      return id_.get(index);
    }
    /**
     * <code>repeated string id = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the id at the given index.
     */
    public com.google.protobuf.ByteString
        getIdBytes(int index) {
      return id_.getByteString(index);
    }
    /**
     * <code>repeated string id = 3;</code>
     * @param index The index to set the value at.
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        int index, String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
      id_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 3;</code>
     * @param value The id to add.
     * @return This builder for chaining.
     */
    public Builder addId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
      id_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 3;</code>
     * @param values The id to add.
     * @return This builder for chaining.
     */
    public Builder addAllId(
        Iterable<String> values) {
      ensureIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, id_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 3;</code>
     * @param value The bytes of the id to add.
     * @return This builder for chaining.
     */
    public Builder addIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIdIsMutable();
      id_.add(value);
      onChanged();
      return this;
    }

    private Object serialNo_ = "";
    /**
     * <code>string serialNo = 4;</code>
     * @return The serialNo.
     */
    public String getSerialNo() {
      Object ref = serialNo_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serialNo_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string serialNo = 4;</code>
     * @return The bytes for serialNo.
     */
    public com.google.protobuf.ByteString
        getSerialNoBytes() {
      Object ref = serialNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serialNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string serialNo = 4;</code>
     * @param value The serialNo to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNo(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      serialNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string serialNo = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSerialNo() {
      
      serialNo_ = getDefaultInstance().getSerialNo();
      onChanged();
      return this;
    }
    /**
     * <code>string serialNo = 4;</code>
     * @param value The bytes for serialNo to set.
     * @return This builder for chaining.
     */
    public Builder setSerialNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      serialNo_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString command_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes command = 5;</code>
     * @return The command.
     */
    @Override
    public com.google.protobuf.ByteString getCommand() {
      return command_;
    }
    /**
     * <code>bytes command = 5;</code>
     * @param value The command to set.
     * @return This builder for chaining.
     */
    public Builder setCommand(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      command_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes command = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommand() {
      
      command_ = getDefaultInstance().getCommand();
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:driver.BatchRunRequest)
  }

  // @@protoc_insertion_point(class_scope:driver.BatchRunRequest)
  private static final BatchRunRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new BatchRunRequest();
  }

  public static BatchRunRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BatchRunRequest>
      PARSER = new com.google.protobuf.AbstractParser<BatchRunRequest>() {
    @Override
    public BatchRunRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BatchRunRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BatchRunRequest> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<BatchRunRequest> getParserForType() {
    return PARSER;
  }

  @Override
  public BatchRunRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

