// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public interface BatchRunResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:driver.BatchRunResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   * @return The request.
   */
  String getRequest();
  /**
   * <code>string request = 1;</code>
   * @return The bytes for request.
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>bytes message = 2;</code>
   * @return The message.
   */
  com.google.protobuf.ByteString getMessage();
}
