// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public final class Driver {
  private Driver() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_HealthCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_Error_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_Error_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_SchemaRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_SchemaRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_SchemaResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_SchemaResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_StartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_StartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_StartResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_StartResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_RunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_RunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_RunResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_RunResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_BatchRunRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_BatchRunRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_BatchRunResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_BatchRunResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_driver_Debug_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_driver_Debug_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014driver.proto\022\006driver\032\tapi.proto\")\n\rUpd" +
      "ateRequest\022\n\n\002id\030\001 \001(\t\022\014\n\004data\030\002 \001(\014\"V\n\010" +
      "Response\022\016\n\006status\030\001 \001(\010\022\014\n\004code\030\002 \001(\005\022\014" +
      "\n\004info\030\003 \001(\t\022\016\n\006detail\030\004 \001(\t\022\016\n\006result\030\005" +
      " \001(\014\"%\n\022HealthCheckRequest\022\017\n\007service\030\001 " +
      "\001(\t\"\300\001\n\023HealthCheckResponse\0229\n\006status\030\001 " +
      "\001(\0162).driver.HealthCheckResponse.Serving" +
      "Status\022\035\n\006errors\030\002 \003(\0132\r.driver.Error\"O\n" +
      "\rServingStatus\022\013\n\007UNKNOWN\020\000\022\013\n\007SERVING\020\001" +
      "\022\017\n\013NOT_SERVING\020\002\022\023\n\017SERVICE_UNKNOWN\020\003\"\220" +
      "\001\n\005Error\022%\n\004code\030\001 \001(\0162\027.driver.Error.Er" +
      "rorCode\022\017\n\007message\030\002 \001(\t\"O\n\tErrorCode\022\n\n" +
      "\006Schema\020\000\022\t\n\005Start\020\001\022\007\n\003Run\020\002\022\t\n\005Write\020\003" +
      "\022\014\n\010BatchRun\020\004\022\t\n\005Debug\020\005\"(\n\007Request\022\017\n\007" +
      "project\030\001 \001(\t\022\014\n\004data\030\004 \001(\014\" \n\rSchemaReq" +
      "uest\022\017\n\007request\030\001 \001(\t\"0\n\014SchemaResult\022\017\n" +
      "\007request\030\001 \001(\t\022\017\n\007message\030\002 \001(\014\"/\n\014Start" +
      "Request\022\017\n\007request\030\001 \001(\t\022\016\n\006config\030\002 \001(\014" +
      "\"/\n\013StartResult\022\017\n\007request\030\001 \001(\t\022\017\n\007mess" +
      "age\030\002 \001(\014\"]\n\nRunRequest\022\017\n\007request\030\001 \001(\t" +
      "\022\017\n\007tableId\030\002 \001(\t\022\n\n\002id\030\003 \001(\t\022\020\n\010serialN" +
      "o\030\004 \001(\t\022\017\n\007command\030\005 \001(\014\"-\n\tRunResult\022\017\n" +
      "\007request\030\001 \001(\t\022\017\n\007message\030\002 \001(\014\"b\n\017Batch" +
      "RunRequest\022\017\n\007request\030\001 \001(\t\022\017\n\007tableId\030\002" +
      " \001(\t\022\n\n\002id\030\003 \003(\t\022\020\n\010serialNo\030\004 \001(\t\022\017\n\007co" +
      "mmand\030\005 \001(\014\"2\n\016BatchRunResult\022\017\n\007request" +
      "\030\001 \001(\t\022\017\n\007message\030\002 \001(\014\"&\n\005Debug\022\017\n\007requ" +
      "est\030\001 \001(\t\022\014\n\004data\030\002 \001(\0142\325\005\n\rDriverServic" +
      "e\022H\n\013HealthCheck\022\032.driver.HealthCheckReq" +
      "uest\032\033.driver.HealthCheckResponse\"\000\022,\n\005E" +
      "vent\022\017.driver.Request\032\020.driver.Response\"" +
      "\000\0221\n\nCommandLog\022\017.driver.Request\032\020.drive" +
      "r.Response\"\000\0226\n\017UpdateTableData\022\017.driver" +
      ".Request\032\020.driver.Response\"\000\022A\n\014SchemaSt" +
      "ream\022\024.driver.SchemaResult\032\025.driver.Sche" +
      "maRequest\"\000(\0010\001\022>\n\013StartStream\022\023.driver." +
      "StartResult\032\024.driver.StartRequest\"\000(\0010\001\022" +
      "8\n\tRunStream\022\021.driver.RunResult\032\022.driver" +
      ".RunRequest\"\000(\0010\001\022=\n\016WriteTagStream\022\021.dr" +
      "iver.RunResult\032\022.driver.RunRequest\"\000(\0010\001" +
      "\022G\n\016BatchRunStream\022\026.driver.BatchRunResu" +
      "lt\032\027.driver.BatchRunRequest\"\000(\0010\001\0221\n\013Deb" +
      "ugStream\022\r.driver.Debug\032\r.driver.Debug\"\000" +
      "(\0010\001\0223\n\014BatchCommand\022\022.api.CreateRequest" +
      "\032\r.api.Response\"\000\0224\n\rChangeCommand\022\022.api" +
      ".UpdateRequest\032\r.api.Response\"\000B;\n cn.ai" +
      "riot.sdk.driver.grpc.driverP\001Z\017./driver;" +
      "driver\210\001\000\240\001\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          cn.airiot.sdk.driver.grpc.api.Api.getDescriptor(),
        });
    internal_static_driver_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_driver_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_UpdateRequest_descriptor,
        new String[] { "Id", "Data", });
    internal_static_driver_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_driver_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_Response_descriptor,
        new String[] { "Status", "Code", "Info", "Detail", "Result", });
    internal_static_driver_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_driver_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_HealthCheckRequest_descriptor,
        new String[] { "Service", });
    internal_static_driver_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_driver_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_HealthCheckResponse_descriptor,
        new String[] { "Status", "Errors", });
    internal_static_driver_Error_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_driver_Error_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_Error_descriptor,
        new String[] { "Code", "Message", });
    internal_static_driver_Request_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_driver_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_Request_descriptor,
        new String[] { "Project", "Data", });
    internal_static_driver_SchemaRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_driver_SchemaRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_SchemaRequest_descriptor,
        new String[] { "Request", });
    internal_static_driver_SchemaResult_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_driver_SchemaResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_SchemaResult_descriptor,
        new String[] { "Request", "Message", });
    internal_static_driver_StartRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_driver_StartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_StartRequest_descriptor,
        new String[] { "Request", "Config", });
    internal_static_driver_StartResult_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_driver_StartResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_StartResult_descriptor,
        new String[] { "Request", "Message", });
    internal_static_driver_RunRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_driver_RunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_RunRequest_descriptor,
        new String[] { "Request", "TableId", "Id", "SerialNo", "Command", });
    internal_static_driver_RunResult_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_driver_RunResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_RunResult_descriptor,
        new String[] { "Request", "Message", });
    internal_static_driver_BatchRunRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_driver_BatchRunRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_BatchRunRequest_descriptor,
        new String[] { "Request", "TableId", "Id", "SerialNo", "Command", });
    internal_static_driver_BatchRunResult_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_driver_BatchRunResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_BatchRunResult_descriptor,
        new String[] { "Request", "Message", });
    internal_static_driver_Debug_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_driver_Debug_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_driver_Debug_descriptor,
        new String[] { "Request", "Data", });
    cn.airiot.sdk.driver.grpc.api.Api.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
