// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public interface ErrorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:driver.Error)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.driver.Error.ErrorCode code = 1;</code>
   * @return The enum numeric value on the wire for code.
   */
  int getCodeValue();
  /**
   * <code>.driver.Error.ErrorCode code = 1;</code>
   * @return The code.
   */
  Error.ErrorCode getCode();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
