// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public interface HealthCheckResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:driver.HealthCheckResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.driver.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.driver.HealthCheckResponse.ServingStatus status = 1;</code>
   * @return The status.
   */
  HealthCheckResponse.ServingStatus getStatus();

  /**
   * <code>repeated .driver.Error errors = 2;</code>
   */
  java.util.List<Error>
      getErrorsList();
  /**
   * <code>repeated .driver.Error errors = 2;</code>
   */
  Error getErrors(int index);
  /**
   * <code>repeated .driver.Error errors = 2;</code>
   */
  int getErrorsCount();
  /**
   * <code>repeated .driver.Error errors = 2;</code>
   */
  java.util.List<? extends ErrorOrBuilder>
      getErrorsOrBuilderList();
  /**
   * <code>repeated .driver.Error errors = 2;</code>
   */
  ErrorOrBuilder getErrorsOrBuilder(
      int index);
}
