// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:driver.Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string project = 1;</code>
   * @return The project.
   */
  String getProject();
  /**
   * <code>string project = 1;</code>
   * @return The bytes for project.
   */
  com.google.protobuf.ByteString
      getProjectBytes();

  /**
   * <code>bytes data = 4;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
