// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:driver.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>string info = 3;</code>
   * @return The info.
   */
  String getInfo();
  /**
   * <code>string info = 3;</code>
   * @return The bytes for info.
   */
  com.google.protobuf.ByteString
      getInfoBytes();

  /**
   * <code>string detail = 4;</code>
   * @return The detail.
   */
  String getDetail();
  /**
   * <code>string detail = 4;</code>
   * @return The bytes for detail.
   */
  com.google.protobuf.ByteString
      getDetailBytes();

  /**
   * <code>bytes result = 5;</code>
   * @return The result.
   */
  com.google.protobuf.ByteString getResult();
}
