// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: driver.proto

package cn.airiot.sdk.driver.grpc.driver;

public interface RunRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:driver.RunRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   * @return The request.
   */
  String getRequest();
  /**
   * <code>string request = 1;</code>
   * @return The bytes for request.
   */
  com.google.protobuf.ByteString
      getRequestBytes();

  /**
   * <code>string tableId = 2;</code>
   * @return The tableId.
   */
  String getTableId();
  /**
   * <code>string tableId = 2;</code>
   * @return The bytes for tableId.
   */
  com.google.protobuf.ByteString
      getTableIdBytes();

  /**
   * <code>string id = 3;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 3;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string serialNo = 4;</code>
   * @return The serialNo.
   */
  String getSerialNo();
  /**
   * <code>string serialNo = 4;</code>
   * @return The bytes for serialNo.
   */
  com.google.protobuf.ByteString
      getSerialNoBytes();

  /**
   * <code>bytes command = 5;</code>
   * @return The command.
   */
  com.google.protobuf.ByteString getCommand();
}
